services:
  matricula267-api:
    build: .
    container_name: matricula267-api
    ports:
      - "127.0.0.1:8267:8000"
    volumes:
      - ./matricula.db:/app/matricula.db
      - ./uploads:/app/uploads
    restart: unless-stopped
